# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=2000)),
                ('auth_count', models.IntegerField(default=0, null=True)),
                ('fake_count', models.IntegerField(default=0, null=True)),
                ('comment_count', models.IntegerField(default=0, null=True)),
                ('rating', models.FloatField(default=0, null=True)),
                ('share_count', models.IntegerField(default=0, null=True)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
