# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_algo', '0002_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='Weight',
            new_name='weight',
        ),
    ]
