# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_algo', '0003_auto_20160818_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
