# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-19 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking_algo', '0004_post_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rank',
            field=models.FloatField(default=0, null=True),
        ),
    ]
